-- Treesitter plugins
require("plugins/treesitter")
require("plugins/treesitter-textobjects")
require("plugins/treesitter-context")

-- Core plugins
require("plugins/plenary")
require("plugins/lspconfig")
require("plugins/autocomplete")
require("plugins/lint")
require("plugins/mini")
require("plugins/dap")
require("plugins/snacks")

-- Themes
require("plugins/tokyonight")

-- Rest
require("plugins/oil")
require("plugins/autopairs")
require("plugins/guess-indent")
require("plugins/todo-comments")
require("plugins/which-key")
require("plugins/conform")
require("plugins/bufjump")
require("plugins/no-neck-pain")
require("plugins/indent-line")
require("plugins/gitsigns")
require("plugins/camelCaseMotion")
require("plugins/comments")
require("plugins/grapple")
require("plugins/roslyn")
require("plugins/easy-dotnet")
require("plugins/csvview")
require("plugins/diffview")
require("plugins/leap")
require("plugins/render-markdown")
require("plugins/smear-cursor")
require("plugins/toggleterm")
require("plugins/treesj")
require("plugins/undo-glow")
require("plugins/windows")
require("plugins/winshift")
require("plugins/zen-mode")
require("plugins/typescript-tools")
require("plugins/copilot")
require("plugins/sidekick")
require("plugins/trouble")
require("plugins/wezterm-types")
require("plugins/neogit")
